### ISSUE TITLE
Update README links or fix Your website's HTTP to HTTPS redirection

### ISSUE THREAD

**Issue by daluu** [poweradminllc/PAExec#40]
This was observed by a friend that the links to http://www.poweradmin.com/paexec, referenced on the README, do not work. I went to check, and the URL is correct, however, the link is HTTP and it just hangs trying to load. When searching PAExec online, it will point to HTTPS version of URL.

So either update the README to reference HTTPS URL or fix your website to auto-redirect HTTP requests to HTTPS.

**Comment by poweradminllc** [comment]
## Reply ABOVE THIS LINE to add a note to this request ##
-------------------------------------------

Thanks for the heads up David.  We recently changed the web server and didn't notice HTTP wasn't working since everything is HTTPS these days.   Fixed.

Doug  
*Power Admin LLC*

> Email: support@poweradmin.com  
>  Web: [](https://www.poweradmin.com/?ref=helpspot) [https://www.poweradmin.com/](https://www.poweradmin.com/)  
>  Support: [](http://support.poweradmin.com/?ref=helpspot) [http://support.poweradmin.com/](http://support.poweradmin.com/)  
>  Twitter: [@poweradmn](http://twitter.com/poweradmn)  
>  Phone: +1 800.401.2339  
>  Fax: +1 866.266.8330


>   If you were delighted by our service, help us get the word out!  
>   Send a tweet, post to a forum, or just tell your buddy.    
>   We would really appreciate it.  Thanks :)  


&gt; David Luu - notifications@github.com (Feb 18 2021, 02:23 PM)
&gt; -----------------------------
&gt; 
&gt; This was observed by a friend that the links to http://www.poweradmin.com/paexec, referenced on the README, do not work. I went to check, and the URL is correct, however, the link is HTTP and it just hangs trying to load. When searching PAExec online, it will point to HTTPS version of URL.
&gt; 
&gt; 
&gt; So either update the README to reference HTTPS URL or fix your website to auto-redirect HTTP requests to HTTPS.
&gt; 
&gt; 
&gt; —
&gt; You are receiving this because you are subscribed to this thread.
&gt; Reply to this email directly, view it on GitHub, or unsubscribe.
&gt;
